# Builda config file
# This file is used to set up your 'builda' commands. Visit https://www.builda.app/setup for more information.

app:
  name: test
  scaffolds:
    - "foxys-own@1.1.0": https://github.com/userspace-apps/scaffolds/tree/master/components/foxys-own
  commands:
    component:
      type: scaffold
      use: foxys-own
      outputPath: './experiments/components'
      substitute:
        prefix':
          - 'atom'
          - 'molecule'
          - 'organism'
    partial:
      type: scaffold
      use: foxys-own
      outputPath: './experiments/partials'
      substitute:
        prefix':
          - 'partial'
