app:
  name: My App
  outputDirectory: ./src
  scaffoldUrl: https://github.com/st-elmos-fire/builda/scaffolds/project/default
scaffolds:
  atom:
    path: ''
    scaffoldUrl: ''
  molecule:
    path: ''
    scaffoldUrl: ''
  organism:
    path: ''
    scaffoldUrl: ''
