# The folder the components will be generated in. This is relative to the buildcomrc file.
output: ./src/components
# Use TypeScript instead of JavaScript? Set to false or omit to disable.
typescript:
# Where should the Prop Types be generated? Inline or separate file?
  inline: Inline
# Generate storybook stories for each component. Set to false or omit to disable.
storybook:
# What format should the storybook use? Set to "mdx" or "csf"
  story_format: CSF
# Generate tests for each component. (Only Jest is supported at the moment.) Set to false or omit to disable.
tests:
# Filename format for test files can be either "spec" or "test", outputs as index.[choice].[ext], where [ext] is based on your answer to "use_typescript".
  extension: test
# Generate a stylesheet for each component. Set to false or omit to disable.
styles:
# Use preprocessor for stylesheets? (can be "sass", "scss" or false)
  preprocessor: CSS
# Use CSS modules?
  modules: false
# Generate a README.md file for each component (recommended unless using MDX for storybook stories).
generate_readme: true
# Generate additional directories for each component (e.g. "images", "helpers", "mocks") (one per line).
extra_directories: false
# If true, example code will be added to the component files. If false, the files will be empty.
prepopulate: true
