# Builda config file# This file is used to set up your 'builda' commands. Visit https://www.builda.app/setup for more information.

app:
  name: test
  outputDirectory: ./test
  scaffoldUrl: http://test.url
scaffolds:
  atom:
    outputDirectory: ''
    scaffoldUrl: ''
  component:
    outputDirectory: ''
    scaffoldUrl: ''
  test:
    outputDirectory: ''
    scaffoldUrl: ''
