# Builda config file
# This file is used to set up your 'builda' commands. Visit https://www.builda.app/setup for more information.

app:
  name: test
  outputDirectory: .
  scaffoldUrl: http://test.url
commands:
  atom:
    type: scaffold
    outputDirectory: './experiments/atom'
    scaffoldUrl: './scaffolds/component-with-storybook'
  component:
    type: scaffold
    outputDirectory: ./components
    scaffoldUrl: https://github.com/userspace-apps/scaffolds/tree/master/components/foxys-own
  test:
    type: scaffold
    outputDirectory: './experiments/test'
    scaffoldUrl: './scaffolds/component-with-storybook'
