// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'example': string;
  'styles--blue': string;
  'styles--red': string;
}
export const cssExports: CssExports;
export default cssExports;
