// This file was automatically generated by [BuildCom](https://www.npmjs.com/package/buildcom)

import React from 'react'

const %ComponentExample% = () => <div></div>


export default %ComponentExample%
