interface ConfigFile {
  /**
   * The resolvers to use for resolving modules (See (https://builda.app/docs/resolvers) for more info)
   */
  resolvers?: {
    [key: string]: string;
  };
  /**
   * Any files or folders from the prefab which you wish to be unique to your app
   */
  ejected?: string[];
  /**
   * Any files or folders in your app which are only used in development and should not be included in the exported app
   * (can be a glob pattern)
   */
  ignored?: string[];
  /**
   * Any blueprint scripts you want to be available to your app (See (https://builda.app/docs/build-a-module/blueprint-scripts) for more info)
   */
  scripts?: {
    [key: string]: BlueprintScriptContents;
  };
  /**
   * The path to the prefab used by your app (can be a local path, a remote url or a resolver)
   */
  prefab?: ModuleConfigContents;
  /**
   * The blueprints to use in your app (See (https://builda.app/docs/blueprints) for more info)
   */
  blueprints?: ModuleConfig;
  /**
   * Any folders that you wish to generate an index file for (See (https://builda.app/docs/build-a-module/gen-index) for more info)
   * (can be a glob pattern)
   */
  indexes?: GenIndexConfig;
  /**
   * A boolean generated by the builda cli to indicate whether the prefab is installed in an app or running directly in development
   * (should not be set manually)
   * @default false
   */
  fromPrefab?: boolean;
}
