app:
    name: My App
    outputDirectory: ./src
    scaffoldUrl: https://github.com/st-elmos-fire/builda/scaffolds/project/default
    scaffolds:
        foxys-own: 1.0.0
commands:
  component:
    type: scaffold
    use: foxys-own
    outputPath: './experiments/components'
    allowedPrefixes:
      - 'atom'
      - 'molecule'
      - 'organism'
